site_name: TEST

theme:
    name: 'material'

extra_javascript:
    - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
    - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'

markdown_extensions:
    - pymdownx.arithmatex